In [11]:
import pandas as pd

data = {
    "OrderID": [101,102,103,104,105,106,107,108],
    "Product": ["Laptop","Phone","Tablet","Shoes","Shoes","Watch","Phone","Laptop"],
    "Category": ["Electronics","Electronics","Electronics","Fashion","Fashion","Accessories","Electronics","Electronics"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Bangalore","Chennai","Delhi","Mumbai"],
    "Sales": [55000,30000,20000,4000,4000,5000,30000,55000],
    "Quantity": [1,2,1,2,2,1,2,1]
}

df = pd.DataFrame(data)
df.head()

   OrderID Product     Category       City  Sales  Quantity
0      101  Laptop  Electronics      Delhi  55000         1
1      102   Phone  Electronics     Mumbai  30000         2
2      103  Tablet  Electronics      Delhi  20000         1
3      104   Shoes      Fashion  Bangalore   4000         2
4      105   Shoes      Fashion  Bangalore   4000         2

In [12]:
df.groupby("Category")["Sales"].sum()

Category
Accessories      5000
Electronics    190000
Fashion          8000
Name: Sales, dtype: int64

In [13]:
df.groupby("Category")["Sales"].sum()

Category
Accessories      5000
Electronics    190000
Fashion          8000
Name: Sales, dtype: int64

In [14]:
df.groupby("Category")["Sales"].count()

Category
Accessories    1
Electronics    5
Fashion        2
Name: Sales, dtype: int64

In [15]:
df["Category"].value_counts()

Category
Electronics    5
Fashion        2
Accessories    1
Name: count, dtype: int64

In [16]:
df.groupby("Category")["Sales"].agg(["sum", "mean", "count"])

                sum     mean  count
Category
Accessories    5000   5000.0      1
Electronics  190000  38000.0      5
Fashion        8000   4000.0      2

In [ ]:
## Reflection
I used groupby() to calculate total, average, and count of sales for each category.
The total sales values matched my Power BI bar chart.
This confirms that both Pandas and Power BI perform the same aggregation operations.
Power BI is easier for visualization, while Pandas provides more flexibility for data analysis.