In [9]:
import pandas as pd

In [10]:
df=pd.read_csv(r"C:\Users\LENOVO\OneDrive\Desktop\internship\day12-dataset.csv")
df.columns

Index(['Row ID', 'Ship Date', 'Order ID', 'Customer ID', 'Ship Mode',
       'Order Date', 'Segment', 'Country', 'City', 'Customer Name',
       'Postal Code', 'Region', 'Sales', 'State', 'Product ID', 'Quantity',
       'Discount', 'Sub-Category', 'Product Name', 'Category', 'Profit'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Ship Date      9994 non-null   object
 2   Order ID       9994 non-null   object
 3   Customer ID    9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Order Date     9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   Customer Name  9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Sales          9994 non-null   object
 13  State          9994 non-null   object
 14  Product ID     9994 non-null   object
 15  Quantity       9994 non-null   int64
 16  Discount       9994 non-null   float64
 17  Sub-Category   9994 non-null   object
 18  Product Name   9994 non-null   object
 19  Category       9994 non-null   object
 20  Profit         9994 non-null   object
dtypes: float64(1), int64(3), object(17)
memory usage: 1.6+ MB

In [12]:


df[["Sales", "Profit"]]

         Sales      Profit
0      ₹ 77.88      ₹ 3.89
1       ₹ 6.63      ₹ 1.79
2       ₹ 5.88      ₹ 1.71
3       ₹ 5.46      ₹ 1.53
4      ₹ 73.20     ₹ 21.23
...        ...         ...
9989    ₹ 4.84    12.09 -₹
9990    ₹ 8.62   2.5872 -₹
9991      ₹ 14      6.3 -₹
9992   ₹ 25.13   6.9102 -₹
9993  ₹ 528.43  143.431 -₹

[9994 rows x 2 columns]

In [ ]:
# This displays two important numeric columns for comparison.

In [13]:
df["Sales"] = df["Sales"].astype(str).str.replace("₹", "").str.replace(",", "").str.strip()
df["Profit"] = df["Profit"].astype(str).str.replace("₹", "").str.replace(",", "").str.strip()
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")
df["Profit"] = pd.to_numeric(df["Profit"], errors="coerce")

In [14]:

df[df["Sales"] > df["Sales"].mean()]

,Row ID,Ship Date,Order ID,Customer ID,Ship Mode,Order Date,Segment,Country,City,Customer Name,...,Region,Sales,State,Product ID,Quantity,Discount,Sub-Category,Product Name,Category,Profit
10,2065,11-Apr-14,CA-2014-106439,GG-14650,Standard Class,31-Oct-14,Corporate,United States,Los Angeles,Greg Guthrie,...,West,405.64,California,OFF-ST-10001963,4,0.00,Storage,Tennsco Regal Shelving Units,Office Supplies,12.17
14,2944,24-Nov-17,CA-2017-126242,MC-18100,Standard Class,19-Nov-17,Consumer,United States,Los Angeles,Mick Crebagga,...,West,305.01,California,OFF-ST-10000675,9,0.00,Storage,"File Shuttle II and Handi-File, Black",Office Supplies,76.25
23,3845,31-Oct-14,CA-2014-101931,TS-21370,First Class,28-Oct-14,Corporate,United States,Los Angeles,Todd Sumrall,...,West,480.74,California,OFF-SU-10000646,2,0.00,Supplies,Premier Automatic Letter Opener,Office Supplies,14.42
30,4487,11-Aug-16,CA-2016-109365,XP-21865,Standard Class,11-Mar-16,Consumer,United States,Los Angeles,Xylona Preis,...,West,314.55,California,OFF-PA-10004359,3,0.00,Paper,Multicolor Computer Printout Paper,Office Supplies,150.98
31,4561,12-Sep-15,CA-2015-118871,HM-14860,Second Class,12-Apr-15,Corporate,United States,Los Angeles,Harry Marie,...,West,271.44,California,OFF-EN-10003296,3,0.00,Envelopes,Tyvek Side-Opening Peel & Seel Expanding Envel...,Office Supplies,122.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,9577,28-May-15,CA-2015-143147,PS-18760,Second Class,26-May-15,Consumer,United States,San Antonio,Pamela Stobb,...,Central,399.54,Texas,TEC-MA-10004679,2,0.40,Machines,StarTech.com 10/100 VDSL2 Ethernet Extender Kit,Technology,NaN
9984,9593,08-Jan-16,US-2016-105452,BF-11005,Standard Class,28-Jul-16,Home Office,United States,Pasadena,Barry Franz,...,Central,302.72,Texas,FUR-FU-10003806,5,0.60,Furnishings,"Tenex Chairmat w/ Average Lip, 45"" x 53""",Furniture,NaN
9986,9625,30-Jun-17,CA-2017-137449,ME-17725,First Class,29-Jun-17,Consumer,United States,Dallas,Max Engle,...,Central,307.31,Texas,FUR-TA-10002855,3,0.30,Tables,Bevis Round Conference Table Top & Single Colu...,Furniture,NaN
9987,9626,30-Jun-17,CA-2017-137449,ME-17725,First Class,29-Jun-17,Consumer,United States,Dallas,Max Engle,...,Central,410.00,Texas,FUR-BO-10000780,3,0.32,Bookcases,O'Sullivan Plantations 2-Door Library in Landv...,Furniture,NaN
9993,9920,19-Mar-16,CA-2016-149272,MY-18295,Standard Class,15-Mar-16,Corporate,United States,Bryan,Muhammed Yedwab,...,Central,528.43,Texas,FUR-CH-10000863,5,0.30,Chairs,Novimex Swivel Fabric Task Chair,Furniture,NaN

In [ ]:
# This shows rows where Sales are higher than average.

In [15]:
df.sort_values(by="Sales", ascending=False)

,Row ID,Ship Date,Order ID,Customer ID,Ship Mode,Order Date,Segment,Country,City,Customer Name,...,Region,Sales,State,Product ID,Quantity,Discount,Sub-Category,Product Name,Category,Profit
9079,2698,23-Mar-14,CA-2014-145317,SM-20320,Standard Class,18-Mar-14,Home Office,United States,Jacksonville,Sean Miller,...,South,22638.48,Florida,TEC-MA-10002412,6,0.5,Machines,Cisco TelePresence System EX90 Videoconferenci...,Technology,NaN
1404,6827,10-Sep-16,CA-2016-118689,TC-20980,Standard Class,10-Feb-16,Corporate,United States,Lafayette,Tamara Chand,...,Central,17499.95,Indiana,TEC-CO-10004722,5,0.0,Copiers,Canon imageCLASS 2200 Advanced Copier,Technology,8399.98
1418,8154,25-Mar-17,CA-2017-140151,RB-19360,First Class,23-Mar-17,Consumer,United States,Seattle,Raymond Buch,...,West,13999.96,Washington,TEC-CO-10004722,4,0.0,Copiers,Canon imageCLASS 2200 Advanced Copier,Technology,6719.98
4815,2624,24-Oct-17,CA-2017-127180,TA-21385,First Class,22-Oct-17,Home Office,United States,New York City,Tom Ashbrook,...,East,11199.97,New York,TEC-CO-10004722,4,0.2,Copiers,Canon imageCLASS 2200 Advanced Copier,Technology,3919.99
1374,4191,22-Nov-17,CA-2017-166709,HL-15040,Standard Class,17-Nov-17,Consumer,United States,Newark,Hunter Lopez,...,East,10499.97,Delaware,TEC-CO-10004722,3,0.0,Copiers,Canon imageCLASS 2200 Advanced Copier,Technology,5039.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8942,2107,26-Sep-14,US-2014-152723,HG-14965,Same Day,26-Sep-14,Corporate,United States,Mesquite,Henry Goldwyn,...,Central,0.88,Texas,OFF-BI-10003460,1,0.8,Binders,Acco 3-Hole Punch,Office Supplies,NaN
8793,4712,31-Mar-14,CA-2014-112403,JO-15280,Same Day,31-Mar-14,Consumer,United States,Philadelphia,Jas O'Carroll,...,East,0.85,Pennsylvania,OFF-BI-10003529,1,0.7,Binders,Avery Round Ring Poly Binders,Office Supplies,NaN
8901,8659,25-Jun-16,CA-2016-168361,KB-16600,Standard Class,21-Jun-16,Corporate,United States,Chicago,Ken Brennan,...,Central,0.84,Illinois,OFF-BI-10003727,1,0.8,Binders,Avery Durable Slant Ring Binders With Label Ho...,Office Supplies,NaN
9056,9293,03-Feb-17,CA-2017-124114,RS-19765,Same Day,03-Feb-17,Corporate,United States,Waco,Roland Schwarz,...,Central,0.56,Texas,OFF-BI-10004022,1,0.8,Binders,Acco Suede Grain Vinyl Round Ring Binder,Office Supplies,NaN
9742,4102,23-Jun-17,US-2017-102288,ZC-21910,Standard Class,19-Jun-17,Consumer,United States,Houston,Zuschuss Carroll,...,Central,0.44,Texas,OFF-AP-10002906,1,0.8,Appliances,Hoover Replacement Belt for Commercial Guardsm...,Office Supplies,NaN

In [ ]:
# This sorts the dataset from highest to lowest Sales.

In [16]:
df[(df["Sales"] > 500) & (df["Profit"] > 100)]

,Row ID,Ship Date,Order ID,Customer ID,Ship Mode,Order Date,Segment,Country,City,Customer Name,...,Region,Sales,State,Product ID,Quantity,Discount,Sub-Category,Product Name,Category,Profit
46,6160,12-Sep-16,CA-2016-161025,GM-14440,Standard Class,12-Mar-16,Consumer,United States,Los Angeles,Gary McGarr,...,West,772.68,California,OFF-ST-10001932,4,0.0,Storage,Fellowes Staxonsteel Drawer Files,Office Supplies,108.18
57,8055,09-Apr-15,CA-2015-121188,CB-12025,Standard Class,28-Aug-15,Consumer,United States,Los Angeles,Cassandra Brandow,...,West,892.35,California,OFF-ST-10001490,5,0.0,Storage,"Hot File 7-Pocket, Floor Stand",Office Supplies,267.71
72,1626,24-Dec-15,CA-2015-157084,JG-15160,Standard Class,19-Dec-15,Consumer,United States,Los Angeles,James Galang,...,West,1265.85,California,TEC-AC-10002049,3,0.0,Accessories,Plantronics Savi W720 Multi-Device Wireless He...,Technology,556.97
92,8587,18-Jul-17,CA-2017-162015,KB-16240,Standard Class,07-Nov-17,Corporate,United States,Los Angeles,Karen Bern,...,West,1287.45,California,TEC-AC-10003832,5,0.0,Accessories,Logitech P710e Mobile Speakerphone,Technology,244.62
112,2405,10-Nov-17,CA-2017-108574,MG-18145,Standard Class,10-Jul-17,Consumer,United States,Los Angeles,Mike Gockenbach,...,West,1115.91,California,TEC-AC-10002049,9,0.0,Accessories,Logitech G19 Programmable Gaming Keyboard,Technology,200.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9539,9406,17-Mar-14,CA-2014-152618,RB-19465,First Class,14-Mar-14,Home Office,United States,Chicago,Rick Bensley,...,Central,574.91,Illinois,TEC-MA-10003626,2,0.3,Machines,Hewlett-Packard Deskjet 6540 Color Inkjet Printer,Technology,156.05
9689,4813,19-Nov-16,CA-2016-121370,EB-14110,Second Class,14-Nov-16,Consumer,United States,Philadelphia,Eugene Barchas,...,East,1199.98,Pennsylvania,TEC-CO-10004115,4,0.4,Copiers,Sharp AL-1530CS Digital Copier,Technology,180.00
9702,6426,27-May-16,CA-2016-143714,CC-12370,Standard Class,23-May-16,Consumer,United States,Philadelphia,Christopher Conant,...,East,8399.98,Pennsylvania,TEC-CO-10004722,4,0.4,Copiers,Canon imageCLASS 2200 Advanced Copier,Technology,1120.00
9718,8124,15-Dec-14,CA-2014-138128,FP-14320,Standard Class,12-Sep-14,Consumer,United States,Philadelphia,Frank Preis,...,East,1079.98,Pennsylvania,TEC-CO-10001766,4,0.4,Copiers,Canon PC940 Copier,Technology,126.00
9726,8800,05-Oct-14,CA-2014-116666,KT-16480,First Class,05-Aug-14,Consumer,United States,Philadelphia,Kean Thornton,...,East,1799.97,Pennsylvania,TEC-CO-10001449,5,0.4,Copiers,Hewlett Packard LaserJet 3310 Copier,Technology,240.00

In [ ]:
# This filters rows where both Sales and Profit are high.